### ISSUE TITLE
Image assets (archiving from wiki)

### ISSUE THREAD

**Issue by boarnoah** [NickGlenn/Unreal-Engine-4-Community-Guide#3]
Hello Nick, 

There are quite a few pages on the wiki that have a lot of image content in them to help illustrate the text. If archiving those into this project do you have a plan on what to do with those assets?

I think the # assets is small enough to just commit directly to git, just want to know whether you have a plan regarding where to store them in the repo (I notice there is a .gitbook/assets folder in the repo). 

Not too sure if that's considered the ideal place to store these image assets.

**Comment by boarnoah** [comment]
PR such as #9 seem to clear it up for me, so drop static assets in .gitbook/assets/<article-title>/

**Comment by wanderrful** [comment]
Yup! More of those issues were fixed in a recent PR that was merged just now. And yes, all pictures go into the folder you mentioned. Thanks for pointing this out!
